import Link from "next/link";
import { Brand } from "@/components/brand";
import { ArrowUpRight, ExternalLink } from "@/components/icons";
import { MarketChart } from "@/components/market-chart";
import { getRwaCandles, getRwaStock } from "@/lib/providers/bitget";
import { getCompanyNews } from "@/lib/providers/finnhub";
import { getRecentFilings } from "@/lib/providers/sec";

export const dynamic="force-dynamic";
export default async function StockPage({params}:{params:Promise<{ticker:string}>}){const{ticker:raw}=await params;const ticker=raw.toUpperCase();const now=new Date();const[stock,chart,news,filings]=await Promise.allSettled([getRwaStock(ticker),getRwaCandles(ticker,"1h",120),getCompanyNews(ticker,new Date(now.getTime()-14*864e5).toISOString().slice(0,10),now.toISOString().slice(0,10)),getRecentFilings(ticker)]);const chartData=chart.status==="fulfilled"?chart.value:{candles:[],freshness:"demo" as const,updatedAt:new Date().toISOString(),source:"Unavailable",error:"Market data unavailable"};const info=stock.status==="fulfilled"?stock.value.value:null;return <main className="stock-page"><nav className="nav shell"><Brand/><div className="nav-links"><Link href="/">Market pulse</Link><Link href="/methodology">Methodology</Link></div><Link className="button button-dark" href={`/desk?q=${encodeURIComponent(`Research ${ticker}`)}`}>Ask Fisk <ArrowUpRight size={15}/></Link></nav><section className="stock-hero shell"><div><span>PUBLIC STOCK OVERVIEW</span><h1>{ticker}</h1><p>{String(info?.name??"US equity and tokenized-market research")}</p></div><div className="stock-quote"><strong>{info?.latest_price?`$${info.latest_price}`:"Price pending"}</strong><span>{info?.price_24h_change_ratio??"Source-labelled chart below"}</span></div></section><section className="stock-content shell"><MarketChart ticker={ticker} initial={chartData}/><div className="stock-columns"><div><header><h2>Company news</h2><span>{news.status==="fulfilled"?`${news.value.items.length} stories`:"Unavailable"}</span></header>{news.status==="fulfilled"&&news.value.items.slice(0,7).map(item=><article className="stock-news" key={item.id}><div><span>{item.source} · {item.freshness}</span><h3>{item.headline}</h3><p>{item.impact}</p></div><a href={item.sourceUrl} target="_blank" rel="noreferrer" aria-label="Open original source"><ExternalLink size={16}/></a></article>)}</div><aside><header><h2>Official filings</h2><span>SEC EDGAR</span></header>{filings.status==="fulfilled"&&filings.value.items.slice(0,5).map(item=><a className="filing-row" href={item.sourceUrl} target="_blank" rel="noreferrer" key={item.id}><b>{item.form}</b><span>{item.filedAt.slice(0,10)}</span><ExternalLink size={13}/></a>)}</aside></div></section></main>}
