"use client";
import { useEffect, useRef, useState } from "react";
import { LineSeries, createChart, type UTCTimestamp } from "lightweight-charts";
import type { Candle } from "@/lib/types";

type Payload={candles:Candle[];freshness:"live"|"cached"|"delayed"|"demo";updatedAt:string;source:string;error?:string};
const ranges=[{label:"1D",period:"5m"},{label:"1W",period:"1h"},{label:"1M",period:"4h"},{label:"3M",period:"1d"},{label:"1Y",period:"1d"},{label:"5Y",period:"1d"}] as const;
export function MarketChart({ticker,initial}:{ticker:string;initial:Payload}){const container=useRef<HTMLDivElement>(null);const[data,setData]=useState(initial);const[range,setRange]=useState("1W");const[loading,setLoading]=useState(false);
  useEffect(()=>{if(!container.current)return;const first=data.candles[0],last=data.candles.at(-1),up=Boolean(last&&first&&last.close>=first.close);const chart=createChart(container.current,{autoSize:true,layout:{background:{color:"transparent"},textColor:"#747474",fontFamily:"JetBrains Mono Variable",fontSize:10},grid:{vertLines:{color:"#e9e9e9"},horzLines:{color:"#e9e9e9"}},rightPriceScale:{borderColor:"#d6d6d6"},timeScale:{borderColor:"#d6d6d6",timeVisible:true,secondsVisible:false},crosshair:{vertLine:{color:"#777",labelBackgroundColor:"#111"},horzLine:{color:"#777",labelBackgroundColor:"#111"}}});const series=chart.addSeries(LineSeries,{color:up?"#16794b":"#b33a3a",lineWidth:3,crosshairMarkerRadius:5});series.setData(data.candles.map(c=>({time:c.time as UTCTimestamp,value:c.close})));chart.timeScale().fitContent();return()=>chart.remove()},[data]);
  async function changeRange(label:string,period:"5m"|"1h"|"4h"|"1d"){setRange(label);setLoading(true);try{const size=label==="5Y"?300:label==="1Y"?260:120;const response=await fetch(`/api/market/rwa/${ticker}/kline?period=${period}&size=${size}`);setData(await response.json())}finally{setLoading(false)}}const first=data.candles[0],last=data.candles.at(-1),direction=last&&first&&last.close>=first.close?"up":"down";
  return <section className="live-chart"><header><div><strong>{ticker} · PRICE HISTORY</strong><span className={`freshness-badge ${data.freshness}`}>{data.freshness}</span></div><div className="chart-controls" aria-label="Chart range">{ranges.map(item=><button className={range===item.label?"active":""} disabled={loading} onClick={()=>changeRange(item.label,item.period)} key={item.label}>{item.label}</button>)}</div></header>{data.candles.length?<div ref={container} className="chart-canvas" aria-label={`${ticker} line chart. ${data.candles.length} observations. Latest price ${last?.close??"unavailable"}, direction ${direction}.`}/>:<div className="chart-unavailable">Price history is unavailable from the current provider.</div>}<footer><span>{data.source}</span><span>Updated {new Date(data.updatedAt).toLocaleString()}</span>{data.error&&<span className="provider-note">Live data unavailable</span>}</footer></section>}
