"use client";
import { useEffect, useRef, useState } from "react";
import { CandlestickSeries, LineSeries, createChart, type UTCTimestamp } from "lightweight-charts";
import type { Candle } from "@/lib/types";

type Payload={candles:Candle[];freshness:"live"|"cached"|"delayed"|"demo";updatedAt:string;source:string;error?:string};
const periods=["5m","15m","1h","4h","1d"] as const;
export function MarketChart({ticker,initial}:{ticker:string;initial:Payload}){const container=useRef<HTMLDivElement>(null);const[data,setData]=useState(initial);const[period,setPeriod]=useState<typeof periods[number]>("1h");const[style,setStyle]=useState<"candles"|"line">("candles");const[loading,setLoading]=useState(false);
  useEffect(()=>{if(!container.current)return;const chart=createChart(container.current,{autoSize:true,layout:{background:{color:"transparent"},textColor:"#858b90",fontFamily:"JetBrains Mono Variable",fontSize:10},grid:{vertLines:{color:"#25292d"},horzLines:{color:"#25292d"}},rightPriceScale:{borderColor:"#34393d"},timeScale:{borderColor:"#34393d",timeVisible:true,secondsVisible:false},crosshair:{vertLine:{color:"#7167df",labelBackgroundColor:"#6357e8"},horzLine:{color:"#7167df",labelBackgroundColor:"#6357e8"}}});const series=style==="candles"?chart.addSeries(CandlestickSeries,{upColor:"#68c2ac",downColor:"#d47867",borderVisible:false,wickUpColor:"#68c2ac",wickDownColor:"#d47867"}):chart.addSeries(LineSeries,{color:"#8f85ff",lineWidth:2});if(style==="candles")series.setData(data.candles.map(c=>({time:c.time as UTCTimestamp,open:c.open,high:c.high,low:c.low,close:c.close})));else series.setData(data.candles.map(c=>({time:c.time as UTCTimestamp,value:c.close})));chart.timeScale().fitContent();return()=>chart.remove()},[data,style]);
  async function changePeriod(next:typeof periods[number]){setPeriod(next);setLoading(true);try{const response=await fetch(`/api/market/rwa/${ticker}/kline?period=${next}&size=120`);setData(await response.json())}finally{setLoading(false)}}const first=data.candles[0],last=data.candles.at(-1),direction=last&&first&&last.close>=first.close?"up":"down";
  return <section className="live-chart"><header><div><strong>{ticker} · UNDERLYING</strong><span className={`freshness-badge ${data.freshness}`}>{data.freshness}</span></div><div className="chart-controls"><button className={style==="candles"?"active":""} onClick={()=>setStyle("candles")}>Candles</button><button className={style==="line"?"active":""} onClick={()=>setStyle("line")}>Line</button>{periods.map(p=><button className={period===p?"active":""} disabled={loading} onClick={()=>changePeriod(p)} key={p}>{p.toUpperCase()}</button>)}</div></header><div ref={container} className="chart-canvas" aria-label={`${ticker} ${style} chart. ${data.candles.length} observations. Latest price ${last?.close??"unavailable"}, direction ${direction}.`}/><footer><span>{data.source}</span><span>Updated {new Date(data.updatedAt).toLocaleString()}</span>{data.error&&<span className="provider-note">Live data unavailable · showing demo snapshot</span>}</footer></section>}
