"use client";
import {useState} from "react";
import {AnimatePresence,motion} from "motion/react";
import {X} from "lucide-react";
import {FiskAvatar} from "@/components/fisk-cat";
import {PromptInput} from "@/components/ui/ai-chat-input";
import type{ResearchResult}from "@/lib/types";

export function StockChat({ticker,initialQuestion=""}:{ticker:string;initialQuestion?:string}){const[open,setOpen]=useState(Boolean(initialQuestion)),[loading,setLoading]=useState(false),[error,setError]=useState(""),[result,setResult]=useState<ResearchResult|null>(null);async function submit(value:string){setOpen(true);setLoading(true);setError("");try{const response=await fetch("/api/research",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({query:value,ticker})});const body=await response.json();if(!response.ok)throw new Error(body.error||"Research failed");setResult(body.result)}catch(value){setError(value instanceof Error?value.message:"Research is unavailable.")}finally{setLoading(false)}}return <><AnimatePresence>{open&&<motion.aside className="stock-chat-panel" initial={{x:50,opacity:0}} animate={{x:0,opacity:1}} exit={{x:50,opacity:0}}><header><FiskAvatar state={loading?"analysing":result?"success":"curious"}/><div><strong>Research {ticker}</strong><span>{loading?"Checking the numbers…":"Ask, challenge, inspect."}</span></div><button onClick={()=>setOpen(false)} aria-label="Close Fisk"><X size={18}/></button></header><div>{loading?<div className="stock-chat-loading"><FiskAvatar state="searching" large/><p>Following the signal…</p></div>:result?<article><h2>{result.directAnswer}</h2><p>{result.thesis}</p>{result.keyFindings.slice(0,4).map(item=><p key={item.claim}>{item.claim}</p>)}</article>:<article><h2>What do you want to know?</h2><p>I’ll connect the chart to reporting, filings, and the argument on the other side.</p></article>}{error&&<p role="alert">{error}</p>}</div><PromptInput onSubmit={(value)=>submit(value)} disabled={loading} placeholder={`Ask Fisk about ${ticker}…`}/></motion.aside>}</AnimatePresence>{!open&&<button className="stock-chat-trigger" onClick={()=>setOpen(true)}><FiskAvatar state="curious"/>Ask Fisk about {ticker}</button>}</>}
